; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
; Default environment
default_envs = seeed_xiao_esp32c6

[env]
; platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.34
framework = arduino
monitor_speed = 115200

; Common build flags for all ESP32-C6 boards
build_flags =

; Common library dependencies for all environments
lib_deps =

[env:seeed_xiao_esp32c6]
board = seeed_xiao_esp32c6
build_flags =
    ${env.build_flags}
    ; -DCORE_DEBUG_LEVEL=5

[env:waveshare_esp32_c6_zero]
board = waveshare_esp32_c6_zero
build_flags =
    ${env.build_flags}
    ; -DCORE_DEBUG_LEVEL=5

[env:makergo_c6_supermini]
board = makergo_c6_supermini
build_flags =
    ${env.build_flags}
    ; -DCORE_DEBUG_LEVEL=5

